name: Veryfi-swift unit test

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Install Swift
        uses: fwal/setup-swift@v1
        with:
          release-version: '5.5.0'
      
      - name: Tests
        run: |
          swift build
          swift test --enable-code-coverage
      
      - name: Generate badge
        run: |
          cd .github/metrics/
          python generate_badge.py
          cd ../../

      - name: Commit Code Coverage Image to Repo
        uses: EndBug/add-and-commit@v5
        with:
          author_name: Github actions
          author_email: veryfi@veryfi.com
          message: "Update report"
          add: "./.github/metrics"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}